version: '3.7'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: 12345678A
      MYSQL_ROOT_PASSWORD: 12345678A
    volumes:
      - mysqldb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - backend-network 

  web:
    stdin_open: true
    tty: true
    container_name: my-bank-api
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PORT: 3333
    volumes:
      - ./:/opt/app
    depends_on:
      mysqldb:
        condition: service_healthy 
    ports:
      - '3333:3333'
      - '5555:5555'
    environment:
      PORT: 3333
    healthcheck:
      test: curl --fail backend:3333/health || exit 1
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - backend-network

networks:
  backend-network:
    name: backend-network
    driver: bridge

volumes:
  mysqldb:
  